### ISSUE TITLE
Incluir as pastas templates/ e static/ em cada aplicação do projeto

### ISSUE THREAD

**Issue by felipebastosweb** [AlbertoAlfredo/ERP_simples#1]
No modo templates e static na pasta ROOT do projeto você tem um design único para todo o projeto. Pode ser interessante colocar estas pastas em cada aplicação do projeto e fazer as configurações devidas ... (Micro_ero/settings.py) para que as aplicações possam ter designs diferenciados.

Vale lembrar que o pacote cliente, produtos, e futuros apps são subaplicacoes e não pastas de domínio. Você pode usar o app produtos como seção do site para o catálogo público e privado dos produtos, e pode usar o app para área reservada do cliente e CRM (Customer Relationship Manager).

No arquivo models.py de cada app vão todas as regras de domínio da aplicação .. mas vc pode criar um pacote chamado, por exemplo, domains/ dentro de cada app e colocar cada classe separado em arquivos diferentes, depois importá-los no arquivo models.py.

**Comment by AlbertoAlfredo** [comment]
Muitissimo obrigado e essa grandiosa melhoria ao qual você me passou a dica ja foi implementada
